Modify `List`/`Set` syntax.
zorp-corp/jock-lang pull request #21
Opened 2024-12-17 18:54 UTC by sigilante

2025-01-06 21:23 UTC, sigilante commented
The former syntax for `let`→`func` required two statements of the input and output types:

```
func a: (@ -> @) = (b:@ -> @) {
  +(b)
};

(b:@ -> @) {
  +(b)
}(23);
```

The new syntax for `func` is simpler to write and closely hews to Swift function declaration syntax:

```
func a(b:@) -> @ {
  +(b)
};

func (b:@) -> @ {+(b)}(23);
```

```
> (mint:jock 'func a(b:@) -> @ {+(b)}; a(23)')
[8 [1 0] [4 0 6] 0 1]

> (mint:jock 'func (b:@) -> @ {+(b)}()')
[7 [8 [1 0] [1 4 0 6] 0 1] 9 2 0 1]

> (mint:jock 'func (b:@) -> @ {+(b)}(23)')
[7 [8 [1 0] [1 4 0 6] 0 1] 9 2 10 [6 7 [0 3] 1 23] 0 1]

> (mint:jock 'func (b:@) -> List(@) {[b +(b)]}(4)')
[7 [8 [1 0] [1 4 0 6] 0 1] 9 2 10 [6 7 [0 3] 1 4] 0 1]

> (mint:jock 'func (b:@) -> Set(@) {{b +(b) +(b)}}(4)')
[7 [8 [1 0] [1 4 0 6] 0 1] 9 2 10 [6 7 [0 3] 1 4] 0 1]
```

2025-01-07 20:51 UTC, sigilante commented
Right now `{}` are doing double duty, but this should be unambiguous due to keywords.

```
let a = {
  3
};

a
```

results in `3`, of type `@`.

```
let a = {
  3
};

a
```

results in `{3}`, of type `Set(@)`.

2025-01-09 22:55 UTC, sigilante commented
Things are looking good here.

I need to update the unit tests now that their code is running, but the syntax switch is complete here.  `/lib/jock` can be reviewed as I anticipate no more changes to it in this PR.

2025-01-09 23:12 UTC, tacryt-socryp reviewed
The joken and jokens rename seems unnecessary, no? A simple find and replace revert of that back to token and tokens would clean up the diff significantly.

2025-01-10 04:14 UTC, sigilante commented
At one point they were different but merged back together.  Easy enough.

2025-01-10 17:02 UTC, tacryt-socryp requested changes

2025-01-10 17:02 UTC, tacryt-socryp commented on hoon/lib/jock.hoon
> +    ::  Fork between a lambda closure and a function definition.
This isn't a fork anymore

2025-01-10 17:02 UTC, tacryt-socryp commented on hoon/lib/jock.hoon
> +        :: (match-inner-jock +>.tokens)
Remove line?

2025-01-10 17:02 UTC, tacryt-socryp commented on hoon/lib/jock.hoon
> +  ?.  ?=(%number -.-.p)
<-.p

2025-01-10 17:02 UTC, tacryt-socryp commented on hoon/lib/jock.hoon
> +  +.-.p
Lark

2025-01-10 17:02 UTC, tacryt-socryp commented on hoon/lib/jock.hoon
> +      :: |^
Commented line extraneous

2025-01-10 17:02 UTC, tacryt-socryp commented on hoon/lib/jock.hoon
> +      ?>  +.+.-.jype
Oof

2025-01-10 17:14 UTC, sigilante commented on hoon/lib/jock.hoon
> +  :: ?:  (has-punctuator -.tokens %'{')
`{` pairs get handled at a different point now so this is a dead code path.  (Downstream of `{}` `Set` notation.)

2025-01-10 17:26 UTC, sigilante commented on hoon/lib/jock.hoon
> +  :: ?:  (has-punctuator -.tokens %'{')
I feel ambivalent about just removing this in case it's necessary later…. probably best to pull it out into a file somewhere.

2025-01-10 17:27 UTC, sigilante commented on hoon/lib/jock.hoon
> +  :: =>  .(tokens `(list token)`tokens)  :: static list typing
actually that whole function can go

2025-01-10 17:27 UTC, sigilante commented on hoon/lib/jock.hoon
> +  :: ?>  (got-punctuator -.+.tokens %'(')
the `match-block` supersedes; removed

2025-01-10 17:45 UTC, sigilante commented on hoon/lib/jock.hoon
> +  [`jype`[;;(jype-leaf [type jyp]) %$] tokens]
need to do some voodoo around the head tag type

2025-01-10 17:46 UTC, sigilante commented on hoon/lib/jock.hoon
> +  [`jype`[;;(jype-leaf [type jyp]) %$] tokens]
this would be easier if Hoon had a way to say "the set of valid head tags over this type"

2025-01-10 17:48 UTC, sigilante commented on hoon/lib/jock.hoon
> +++  match-metatype
done

2025-01-10 17:56 UTC, sigilante commented on hoon/lib/jock.hoon
> +  ?.  ?=(%number -.-.p)
I could live with `--+-+` or something but the alternating notation is just absolute wretched

2025-01-10 18:37 UTC, sigilante commented on hoon/lib/jock.hoon
> +  [`jype`[;;(jype-leaf [type jyp]) %$] tokens]
I tried a few things; there appears to be no straightforward way to do this without `;;`.

2025-01-10 18:47 UTC, sigilante commented
@tacryt-socryp everything resolved here except `;;` which has to stay because of Hoon typing.

`/lib/jock` “ready”.  Going to set up unit tests really quick then we're good to go.

2025-01-10 19:15 UTC, tacryt-socryp approved these changes

2025-01-10 21:24 UTC, sigilante commented
Blocked on CI.  If `/mar/jock` is not necessary it can be removed.

2025-01-13 15:58 UTC, merged